[package]
name = "rustbuster"
version = "0.12"
authors = ["nxnjz <nxnjz@nxnjz.net>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
reqwest = "0.9"
dns-lookup = "1.0.0"
base64 = "0.10"
indicatif = "0.11"
